### ISSUE TITLE
gradient operator for NEMO variables: d(grid_t)/dz --> grid_w

### ISSUE THREAD

**Issue by jpolton** [British-Oceanographic-Data-Centre/COAsT#100]
Derivatives of variables have precise definitions on the NEMO grid that should be made reproducible offline as an accessible method for NEMO objects.

branch: https://github.com/British-Oceanographic-Data-Centre/COAsT/tree/0100_gradients

Story:
scientist wants to compute stratification. Call a method to get it. Needs to handle grids in an appropriate way.

AC:
Want something like this to work: derivative( var, dim_name).
Return an xarray DataArray with appropriate attributes.
It would be nice to be able to compute E.g. d(rho)/dz and d(SSH)/dx

**Comment by jpolton** [comment]
This led to:
1. introducing some new attributes for the nemo data on load.
2. Proposing a get_depth_as_xr method like @anwiseNOCL but keeping stuff in xarrays - hoping that one day dask will be needed.  
3. Defining a derivative method (it is a template really) that does derivatives using grid attributes and preserving xarray properties.

**Comment by anwiseNOCL** [comment]
@jpolton On point 3. Following the discussion I started putting the get_depth functionality into the class, such that it will be calculated and then added into the objects xarray dataset. There needs to be one for Domain, which is the time zero depths and one for Nemo, which can allow time evolution.  I **hope** to finally pull request that branch soon so I suggest you look at it what I have done and then make updates if needed in this issue.

**Comment by jpolton** [comment]
> @jpolton On point 3. Following the discussion I started putting the get_depth functionality into the class, such that it will be calculated and then added into the objects xarray dataset. There needs to be one for Domain, which is the time zero depths and one for Nemo, which can allow time evolution. I **hope** to finally pull request that branch soon so I suggest you look at it what I have done and then make updates if needed in this issue.

This sounds great. Can you update the remote origin https://github.com/British-Oceanographic-Data-Centre/COAsT/tree/0048/transect_transport branch so I can update with your modifications. (A pull request needs unit testing and all that, which isn't necessary for this discussion)

**Comment by jpolton** [comment]
Derivatives are computed in x_dim, y_dim, z_dim (or i,j,k) directions
        wrt lambda, phi, or z coordinates (with scale factor in metres not degrees).

        Derivates are 1st order centre differences as this is what NEMO (and its
        conservation properties use), rather than some fancy high order schemes.

        Equations taken from 3.1.2 of the NEMOv4 handbook for the definition of
        "grad q"

        Currently the method does not accomodate all possible eventualities. It
        covers:
        1) d(grid_t)/dz --> grid_w

        Returns  an object (with the appropriate target grid_ref) containing
        derivative (out_varstr) as xr.DataArray

        This is hardwired to expect:
        1) depth_0 and e3_0 fields exist
        2) xr.DataArrays are 4D
        3) self.filename_domain if out_obj not specified

        Example usage:
        --------------
        # Initialise DataArrays
        nemo_t = coast.NEMO( fn_data, fn_domain, grid_ref='t-grid' )
        # Compute dT/dz
        nemo_w_1 = nemo_t.differentiate( 'temperature', dim='z_dim' )

        # For f(z)=-z. Compute df/dz = -1. Surface value is set to zero
        nemo_t.dataset['depth4D'],_ = xr.broadcast( nemo_t.dataset['depth_0'], nemo_t.dataset['temperature'] )
        nemo_w_4 = nemo_t.differentiate( 'depth4D', dim='z_dim', out_varstr='dzdz' )

        Provide an existing target NEMO object and target variable name:
        nemo_w_1 = nemo_t.differentiate( 'temperature', dim='z_dim', out_varstr='dTdz', out_obj=nemo_w_1 )
    

        Parameters
        ----------
        in_varstr : str, name of variable to differentiate
        dim : str, dimension to operate over. E.g. {'z_dim', 'y_dim', 'x_dim', 't_dim'}
        out_varstr : str, (optional) name of the target xr.DataArray
        out_obj : exiting NEMO obj to store xr.DataArray (optional)

        """
