### ISSUE TITLE
Depth coordinate for u,v,f grids

### ISSUE THREAD

**Issue by jpolton** [British-Oceanographic-Data-Centre/COAsT#118]
Currently we are using depth_t as the vertical coordinate for u,v and f grid variables.
This is OK as long as it is only used for plotting. 

Do we want a 'proper' `depth_u`etc ?

This is calculated and assigned on data loading in the NEMO class.

**Comment by anwiseNOCL** [comment]
This has now been done using the initial time zero depths. Providing we don't require the time-dependent depths then this can be moved to Done when Branch #105 is merged with Develop
