### ISSUE TITLE
Warning messages during Nemo object initialization

### ISSUE THREAD

**Issue by anwiseNOCL** [British-Oceanographic-Data-Centre/COAsT#123]
**Issue:**
When creating a NEMO object variables and dimensions are renamed. This causes warning messages when the things to be renamed are not found. This is good except that multiple warnings for the same variable are produced. For example, the code will look for multiple different names of the temperature variable. As a next step we need to refine this so that only one message per variable and dimension is generated. 

**A/C**
One warning message per variable or dimension generated when not found for renaming.

**Comment by jpolton** [comment]
At present warnings are just surpressed. This sort of works.

**Comment by jpolton** [comment]
Changed the logging level to suppress DEBUG comments
