### ISSUE TITLE
Create a log object, or attribute to NEMO class?

### ISSUE THREAD

**Issue by jpolton** [British-Oceanographic-Data-Centre/COAsT#131]
I notice we are writing lots of helpful print statements that we then comment out once stuff works. How about having a method something like:

```
def debug(self, str):
  """
  Example usage:
    debug('Print-statement-content')
  """
  self += str+"\n"
```

which would somehow have an option to be silent or verbose.

Other useful info would be the filename and line number. This might do that:
```
from inspect import getframeinfo, stack

def log(message):
    caller = getframeinfo(stack()[1][0])
    print "%s:%d - %s" % (caller.filename, caller.lineno, message)
```

Example usage: `log("aargh")`

**Comment by malhearn** [comment]
Proposed solution:
Use python logging module
Use flags (error, warnings etc) to direct logging to particular locations

**Comment by matt-caz** [comment]
@jpolton Is the scope of this ticket limited to NEMO or are you thinking of the whole codebase?

**Comment by jpolton** [comment]
> @jpolton Is the scope of this ticket limited to NEMO or are you thinking of the whole codebase?

I was thinking the whole code base. The use case being that it would provide insight into how stuff breaks when running unit testing.
