### ISSUE TITLE
Check Lazy loading

### ISSUE THREAD

**Issue by davbyr** [British-Oceanographic-Data-Centre/COAsT#144]
look into lazy loading in xarray and see if you can determine what is in memory and what is on disk. 

This has an impact as dataset grow in size. 

AC 
The ability to check if a variable is in-memory or being read off disk

**Comment by malhearn** [comment]
Share code debugging best practice within IDE?
Use python debugging method to illustrate when data has been loaded to memory
Links to DASK behavior as indicator of memory usage
Test on JASMIN?
