### ISSUE TITLE
Description of what COAsT does?

### ISSUE THREAD

**Issue by DanJonesOcean** [British-Oceanographic-Data-Centre/COAsT#153]
Hello,

This software looks potentially interesting, but it's not clear what it actually does. Could you add a description of what the software does to the documentation? What are the inputs and outputs? The documentation on the project's associated website seems to be generic. 

Thanks,
Dan

**Comment by jpolton** [comment]
> Hello,
> 
> This software looks potentially interesting, but it's not clear what it actually does. Could you add a description of what the software does to the documentation? What are the inputs and outputs? The documentation on the project's associated website seems to be generic.
> 
> Thanks,
> Dan

Thanks @DanJonesOcean for pointing this out. We will update in the meantime I can answer with another generic statement just added to the code repo README: "COAsT is Diagnostic and Assessment toolbox for kilometric scale regional models.
It's aim is to deliver a flexible, community-ready framework for assessing kilometric scale ocean models. The focus, initially, is be on delivering novel diagnostics for processes that are emergent at the kilometric scale and with NEMO model output. The framework leans heavily on xarray."

Specifically we have been working on i) merging NEMO output and their grid information for easier manipulation; ii) Continuously Ranked Probability diagnostics for (e.g.) sea surface height validation; iii) internal tide diagnostics; and iv) transect diagnostics.

In the future we will add some more standard diagnostics that we use to validate NEMO configs before the go operational (on a different funding stream). We will also (hopefully) add additional model flavours (e.g. FVCOM and ROMS)

**Comment by DanJonesOcean** [comment]
Thanks very much!

**Comment by jpolton** [comment]
> Thanks very much!

We've done a bit more to update the docsy site (https://british-oceanographic-data-centre.github.io/COAsT/docs/). Though it will never be static for a long as we are funded to develop it. Thanks for taking the time to raise this Issue.

**Comment by jpolton** [comment]
> Thanks very much!

We've done a bit more to update the docsy site (https://british-oceanographic-data-centre.github.io/COAsT/docs/). Though it will never be static for a long as we are funded to develop it. Thanks for taking the time to raise this Issue.
