### ISSUE TITLE
Unit Test/Example scripts Accessible from Conda Install

### ISSUE THREAD

**Issue by davbyr** [British-Oceanographic-Data-Centre/COAsT#167]
What is the best way to make these scripts accessible from the conda install? It doesn't appear to be in the environment source code.

**Comment by jpolton** [comment]
Proposed solution is to embed the example_scripts into the COAsT-site repo, somehow.

**Comment by jpolton** [comment]
This is not really necessary: unit testing files can be obtained with a git clone.
