### ISSUE TITLE
Zenodo publishing

### ISSUE THREAD

**Issue by jpolton** [British-Oceanographic-Data-Centre/COAsT#171]
Keeping track of Zenodo publishing.

Issues / queries:

* 2 repos but one zenodo object. (Probably just have COAsT-site as a related, and separate, untracked entity)
* We need to make a release and test it a bit (which will take a bit of time) before we mint the doi.
* Target data for publishing: end of Sept (after the Sprint)
* Other Things

[EDIT] Summary/Conclusion:

* Git publish tagged releases of the codebase often - zenodo will keep track
* Desirable to make pdf snapshot versions of docsy site to attach as git attributes to a tagged release (perhaps as a git action)
* live COAsT-site url can be linked to Zenodo as a linked resource.

**Comment by jpolton** [comment]
@thogar-computer  I’ve just checked and the British-Oceanographic-Data-Centre github ‘institution’ is not talking to Zenodo.
My JMMP-Group and NOC-MSM github ‘institutions’ can. I think I had to flick a switch to permit this. But I can’t do that for British-Oceanographic-Data-Centre

**Comment by thogar-computer** [comment]
this might be a permissions issue, as i have it linked on my Zenodo account... i will look and see if that the case.

**Comment by thogar-computer** [comment]
@jpolton as for the docsy site, i was thinking, the team could make a new docsy release each time a COAsT package is released, the zenodo DOI metadata (under Related/alternate identifiers) is then updated to include a link to the zipped docs ?

**Comment by thogar-computer** [comment]
i have update the groups permissions to maintainor, will be interesting to see if that allows the zenodo linking to be done by any one

**Comment by jpolton** [comment]
> i have update the groups permissions to maintainer, will be interesting to see if that allows the zenodo linking to be done by any one

The computer says no.

**Comment by jpolton** [comment]
> @jpolton your now an admin... what does it say?

Can you get on Teams, Zoom, share a telephone number, or pass a yoghurt pot and string?

**Comment by jpolton** [comment]
![screenshot](https://user-images.githubusercontent.com/22616872/93612299-433b7680-f9c7-11ea-94e1-60b783d3cf31.png)

![screenshot](https://user-images.githubusercontent.com/22616872/93612346-4e8ea200-f9c7-11ea-9e01-90ac288f8754.png)

Something in "Third Party apps" needs to be clicked. I can not access this setting with my meagre privelidges

**Comment by thogar-computer** [comment]
so that flag is set, i am wondering if this is because it is already set-up in my zenodo account... 
![image](https://user-images.githubusercontent.com/17544535/93744747-4498b900-fbea-11ea-89e5-1ee1a2ea98ad.png)
