### ISSUE TITLE
GSW version problem

### ISSUE THREAD

**Issue by davbyr** [British-Oceanographic-Data-Centre/COAsT#199]
In requirements.txt, gsw needs its version fixed to 3.3.1.

**Comment by jpolton** [comment]
I've added a text file ``COAsT/conda_requirements.txt`` which states the requirements for a conda environment developer build. These are currently:

numpy>=1.16
dask>=2
dask[complete]>=2
xarray>=0.1
matplotlib>=3
netCDF4>=1
scipy>=1
gsw==3.3.1
scikit-learn>=0.2
scikit-image>=0.15
cartopy
spyder>=4

They are a modification of ``requirements.txt`` used by the auto build process.
These files will need to be updated when if/when `gsw` is updated.
