### ISSUE TITLE
Find High Waters for time series

### ISSUE THREAD

**Issue by davbyr** [British-Oceanographic-Data-Centre/COAsT#220]
Adapt old methods for locating optima in a time series.

**Comment by jpolton** [comment]
I would probably be good if the method to do this made an xarray object like TIDEGAUGE with times as coordinates (which would be non regular) and perhaps the data are returned between two input dates (for consistency across the class). Then it would also look like the timetable xr.DataArrays.

I can imagine it would be useful to have some flexibility here in how the values and time are obtained. So though we will start with something, I forsee additional approaches to sampling the data would be useful too. For example a cubic spline on the data to extract extrema could be useful for some applications, whereas nearest neighbour would be better for others. Also I am thinking that steepest rate of change might also be an interesting thing to grab (HT in places like Southampton are stationary for a long time so time(HT) is hard to score against, but perhaps time of max d(SSH)/dt might be interesting... maybe...)
The point being if we are mindful of enhancements they can be borne in mind when the template is set out.
