### ISSUE TITLE
find_maxima() problems

### ISSUE THREAD

**Issue by davbyr** [British-Oceanographic-Data-Centre/COAsT#267]
@jpolton  Been trying to use your fancy new find_maxima cubic method, but having problems when applying it to a TIDEGAUGE object with GESLA data in. Also when trying to use the stats_util method directly on xarray data (so passing DataArrays of time and heights straight to find_maxima). 

When applying to a TIDEGAUGE object with GESLA data in it:

```
RuntimeError: NumPy datetime metadata is corrupted with invalid base unit

SystemError: <built-in function ensure_datetime64ns> returned a result with an error set
```

Or trying to use stats_util.find_maxima:

```
test = su.find_maxima(port_mod.time, xr.DataArray(mod_rec, dims='t_dim'), method='cubic')

ValueError: Cannot convert a NumPy datetime value other than NaT with generic units
```

The stats_util one is particularly strange because the method will run and complete but the error doesn't come up until you try and interrogate the output.

POTENTIAL FIX: 
I think the problem is happening at the return statement. I found replacing the call to `return extr_x_vals[ind].astype('datetime64'), max_vals` with the pandas routine `return pd.to_datetime(extr_x_vals[ind]), max_vals` seemed to stop the problem.

Not sure why however.

**Comment by jpolton** [comment]
Hmm I don't have an issue with the first point. I just tested this on develop and it made a plot as expected.

```
import coast
import datetime
import numpy as np
import matplotlib.pyplot as plt

# And by defining some file paths
fn_tidegauge = './example_files/tide_gauges/lowestoft-p024-uk-bodc'

# we load data between two specified dates:
date0 = datetime.datetime(2007,1,10)
date1 = datetime.datetime(2007,1,16)
tg = coast.TIDEGAUGE(fn_tidegauge, date_start = date0, date_end = date1)

extrema_comp = tg.find_high_and_low_water('sea_level', method="comp")

# Use cubic spline fitting method
extrema_cubc = tg.find_high_and_low_water('sea_level', method="cubic")

# Plot to show the difference between maxima find methods for high tide example.
plt.figure()
plt.plot(tg.dataset.time, tg.dataset.sea_level, 'k')
plt.scatter(extrema_comp.dataset.time_highs.values, extrema_comp.dataset.sea_level_highs, marker='o', c='g')
plt.scatter(extrema_cubc.dataset.time_highs.values, extrema_cubc.dataset.sea_level_highs, marker='+', c='g')
plt.xlim([date0, date1])
plt.legend(['Time Series','Maxima by comparison','Maxima by cubic spline'])
plt.title(f'Tide Gauge Optima at {tg.dataset.site_name}')
plt.show()

```
 
It does find local extrema though, which might be an issue with noisy data.
Is there a specific thing you were doing that didn't work?

The second issue is concerning. I have just tried my 'working' example and it shows a problem too if using the find_maxima() explicitly. I will have a poke around.

**Comment by jpolton** [comment]
Dark things occur when switch between time formats and things can go wrong due to time zone issues. Numpy and datetime seem to be in a state of dev flux on this issue, and pandas is not currently invoked.  So I decided to code my own conversion of np.datetime64 to float that I can exactly reverse. In the future this probably won't be needed.

Also notice the method='comp' preserved xr.DataArray for input to output. Added this for method='cubic'.

However, I am not done as method='cubic' does not pick up all these extrema expected in the example in the find_maxima() doc str....

**Comment by jpolton** [comment]
@davbyr I now understand why the pandas solution works but am wary of inconsistencies creeping in with different tools for converting to and from datetime64 (timezones could be an issue). So I have done the transformation manually. 

I've started a new pull request in draft and added stat_util.find_maxima() explicitly to unit_testing. It all seems more robust now. But perhaps you can make it break with your previous tests?
