### ISSUE TITLE
Automatic conda publishing (BODCDMSYS-2187)

### ISSUE THREAD

**Issue by jpolton** [British-Oceanographic-Data-Centre/COAsT#37]
n the interest of reproducibility and reducing future maintenance overheads, we want to set up a GitHub Actions workflow to automate build and deployment of the COAsT package to Anaconda. We currently have the equivalent set up for PyPi deployment, so this will give us a complete setup. 

We'll probably want to include this functionality in the existing PyPi deployment workflow, so that if build or deployment to PyPi fail (for instance, when the version number hasn't been updated), then deployment to Anaconda won't happen. 

Given: We can automatically deploy the package to PyPi. 
When: The master branch is pushed to with a new version 
Then: The package is built and deployed to the BODC organisation on Anaconda Cloud. 

AC 

We have a functional workflow that automatically deploys to Anaconda Cloud on push to the master branch. 
UAC - Dave to check with some code changes of his own.

**Comment by jpolton** [comment]
Auto publishing to conda is not currently working.

Since last time (at least one) new package is required: ``conda install -c conda-forge gsw``

**Comment by davbyr** [comment]
@matt-caz @jpolton I've brought the master branch up to date with develop + the new anaconda build fixes but it still looks as if the automatic build isn't happening.

**Comment by Fakas** [comment]
@davbyr The error we're seeing there is because develop was merged without updating the package version number. We can make the change directly to master to expedite the process. Do you want to do that or shall I do it?

**Comment by matt-caz** [comment]
Apologies, commented above with my personal account.

**Comment by davbyr** [comment]
@matt-caz It might be good for me to do it if this will be done every time a new master is pushed. What do I need to do?

**Comment by matt-caz** [comment]
@davbyr See package.json at the top level of the repo. The "version" key has the value "0.2.1a10". a16 is the latest version on PyPi so I'd suggest changing it to "0.2.1a17".

**Comment by davbyr** [comment]
@matt-caz Done but now there's a new problem.. It's published to PyPi successfully but not Anaconda.

**Comment by matt-caz** [comment]
"Couldn't extract raw recipe text for coast output" is the error, which I don't think I've seen before. Looking into it.

**Comment by davbyr** [comment]
Sorry @matt-caz, I made a tiny change to master and pushed (a comment in TIDEGAUGE), but it is getting stuck at publishing to pip:

```
Run ./publish.sh "https://upload.pypi.org/legacy/" "$PYPI_TOKEN"
Uploading distributions to https://upload.pypi.org/legacy/
Uploading COAsT-0.2.1a37-py3-none-any.whl

  0%|          | 0.00/42.5k [00:00<?, ?B/s]
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
File already exists. See https://pypi.org/help/#file-name-reuse for more information.
100%|██████████| 42.5k/42.5k [00:00<00:00, 179kB/s]
NOTE: Try --verbose to see response content.
##[error]Process completed with exit code 1.
```

I think we've had this one before? Was it a version number thing?
