### ISSUE TITLE
Set up Hugo workflow for documentation

### ISSUE THREAD

**Issue by jpolton** [British-Oceanographic-Data-Centre/COAsT#38]
Locally set up tools for building documentation. See : https://british-oceanographic-data-centre.github.io/COAsT/docs/contribution-guidelines/

Acceptance criteria: we can each preview webpage docs

**Comment by jpolton** [comment]
We can close this when we three can do the Hugo thing

**Comment by thogar-computer** [comment]
@jpolton @davbyr - I recommend that you merge master into development for the COAsT-site repo before an major update/work takes place - some edits have been applied to master that will be missing on develop, these might otherwise be lost/overwritten.

**Comment by jpolton** [comment]
@thogar-computer @davbyr Good point. I've merged master back into develop.
_For reference:_
`
git checkout develop
git merge master
`

**Comment by jpolton** [comment]
@thogar-computer Looking at the Contribution Guidline for [local previewing](https://british-oceanographic-data-centre.github.io/COAsT/docs/contribution-guidelines/#previewing-your-changes-locally). Item 2:

> Fork the COAsT-site repo repo into your own project, then create a local copy using git clone. Don’t forget to use --recurse-submodules or you won’t pull down some of the code you need to generate a working site.

Did this mean "(we) Fork(ed) the docsy repo. Now _you_ clone the COAsT-site"? I.e. Do I really need two copies of COAsT-site?

**Comment by thogar-computer** [comment]
so for team members a fork isn't required, you can clone the repo and work in the development branch, then review and merge via pull requests. 

For external contributers, I think forking the COAsT repo is the best way forward. Their changes can be reviewed via a pull request to develop and then we can 'bundle changes' from develop to master (via another pull request).

**Comment by jpolton** [comment]
@anwiseNOCL @davbyr - I can preview the docs using hugo. We will close this when you are happy you can too.

**Comment by jpolton** [comment]
@anwiseNOCL  and @jpolton are content with this

**Comment by davbyr** [comment]
@jpolton @thogar-computer Can I check that I am meant to run `hugo server` when inside COAsT-site? I get the error:

```
Error: Error building site: "/Users/Dave/Documents/Projects/WCSSP/COAsT-site/content/en/_index.html:7:1": failed to extract shortcode: template for shortcode "blocks/cover" not found
```

**Comment by thogar-computer** [comment]
i think you need to do a sub clone

https://www.atlassian.com/git/tutorials/git-submodule#:~:text=Cloning%20git%20submodules,init%20will%20update%20the%20local%20.

so either a 

git submodule init
git submodule update

or re clone with the following flag
-recursive
git clone -recursive <linkl>

**Comment by davbyr** [comment]
@thogar-computer Yep, `--recurse-submodules` did it. Sorry, I missed that line in the docs.

**Comment by davbyr** [comment]
@jpolton @thogar-computer Got this working, will close this issue, add the README onto the website then open a new pull request on COAsT-site.
