### ISSUE TITLE
Update example files

### ISSUE THREAD

**Issue by davbyr** [British-Oceanographic-Data-Centre/COAsT#385]
Update example files:

1. Anna's 2 file example files:
    a. SEASIA domain
    b. SEASIA example data
    c. mesh_mask.

2. Catch up with previous files

**Comment by jpolton** [comment]
```
/projectsa/COAsT/NEMO_example_data/SEAsia_R12/coast_example_domain_SEAsia.nc 
/projectsa/COAsT/NEMO_example_data/SEAsia_R12coast_example_SEAsia_BGC_1990.nc 
/projectsa/COAsT/NEMO_example_data/SEAsia_R12/example_nemo_BGC.json 
```

**Comment by jpolton** [comment]
I think I've got things in a mess with file names. Does someone have a "master" copy of `example_files` that I can start again with?

Did I mirror this directory in /projectsa/COAst ?...

**Comment by katavouta** [comment]
> ```
> /projectsa/COAsT/NEMO_example_data/SEAsia_R12/coast_example_domain_SEAsia.nc 
> /projectsa/COAsT/NEMO_example_data/SEAsia_R12coast_example_SEAsia_BGC_1990.nc 
> /projectsa/COAsT/NEMO_example_data/SEAsia_R12/example_nemo_BGC.json 
> ```

You also need the wod files

**Comment by katavouta** [comment]
> ```
> /projectsa/COAsT/NEMO_example_data/SEAsia_R12/coast_example_domain_SEAsia.nc 
> /projectsa/COAsT/NEMO_example_data/SEAsia_R12coast_example_SEAsia_BGC_1990.nc 
> /projectsa/COAsT/NEMO_example_data/SEAsia_R12/example_nemo_BGC.json 
> ```

You also need the WOD file : /projectsa/COAsT/NEMO_example_data/SEAsia_R12/WOD_example_ragged_standard_level.nc
