### ISSUE TITLE
Update docs with changes

### ISSUE THREAD

**Issue by davbyr** [British-Oceanographic-Data-Centre/COAsT#394]
AC:
Docs updated with all new things. Check old things work. Put edits into the develop branch of COAsT-site and tick when done

Update Getting Started:
- [ ] [Getting Started](https://british-oceanographic-data-centre.github.io/COAsT/docs/getting-started/) @jpolton 

Update/Check Examples:

- [x] [Altimetry](https://british-oceanographic-data-centre.github.io/COAsT/docs/examples/altimetry/) @whoever
- [x] [Climatology](https://british-oceanographic-data-centre.github.io/COAsT/docs/examples/climatology/) @whoever 
- [ ] [Profile](https://british-oceanographic-data-centre.github.io/COAsT/docs/examples/profile/) @davbyr 
- [x] [Tidegauge](https://british-oceanographic-data-centre.github.io/COAsT/docs/examples/tidegauge/) @davbyr 
- [x] [TidegaugeMultiple](https://british-oceanographic-data-centre.github.io/COAsT/docs/examples/tidegaugemultiple/) @davbyr 
- [x] [Contours](https://british-oceanographic-data-centre.github.io/COAsT/docs/examples/contour/) @anwiseNOCL 
- [x] [Transects](https://british-oceanographic-data-centre.github.io/COAsT/docs/examples/transect/) @anwiseNOCL 
- [x] [EOFs](https://british-oceanographic-data-centre.github.io/COAsT/docs/examples/eofs/) @anwiseNOCL 
- [x] [Stratification diagnostics](https://british-oceanographic-data-centre.github.io/COAsT/docs/examples/stratification/) @jpolton / @whoever
- [x] [Export to netCDF](https://british-oceanographic-data-centre.github.io/COAsT/docs/examples/export_netcdf/) @jpolton / @whoever 

---

- [ ] Julia - CMEMS example (www / script)
- [x] Anna - BGC example (www)
- [x] Jeff - tidegauge (www / scripts)
- [ ] Anthony - profile (www / scripts)
- [x] Anna - climatology ( www )

**Comment by katavouta** [comment]
I am testing the example for climatology. Maybe I am doing something wrong but for me the example does not work: 

climatology_frequency = "month" 
clim = coast.Climatology()
# Not writing output to file:
clim_mean = clim.make_climatology(nemo, climatology_frequency)

Gives error: 
File "/tmp/ipykernel_85931/1559894460.py", line 6, in <cell line: 6>
    clim_mean = clim.make_climatology(nemo, climatology_frequency)

  File "/work/annkat/COAST_DEV/COAsT/coast/climatology.py", line 63, in make_climatology
    for var_name, da in ds.data_vars.items():

AttributeError: 'Gridded' object has no attribute 'data_vars'

**Comment by jpolton** [comment]
> I am testing the example for climatology. Maybe I am doing something wrong but for me the example does not work:
> 
> climatology_frequency = "month" clim = coast.Climatology()
> 
> # Not writing output to file:
> clim_mean = clim.make_climatology(nemo, climatology_frequency)
> 
> Gives error: File "/tmp/ipykernel_85931/1559894460.py", line 6, in <cell line: 6> clim_mean = clim.make_climatology(nemo, climatology_frequency)
> 
> File "/work/annkat/COAST_DEV/COAsT/coast/climatology.py", line 63, in make_climatology for var_name, da in ds.data_vars.items():
> 
> AttributeError: 'Gridded' object has no attribute 'data_vars'

Hmmm @katavouta. I agree. @davbyr do you know what happened here?

**Comment by katavouta** [comment]
Checked the example for the Export to netCDF and everything works fine so I will tick it.

**Comment by katavouta** [comment]
@davbyr I am having a look in the Tidegauge example: https://british-oceanographic-data-centre.github.io/COAsT/docs/examples/tidegauge/

and there is a typo initially that causes problems (an extra comma after the config file):
fn_config_t_grid = './config/example_nemo_grid_t.json',
fn_tidegauge = './example_files/tide_gauges/lowestoft-p024-uk-bodc'

such that it should be:
fn_config_t_grid = './config/example_nemo_grid_t.json'
fn_tidegauge = './example_files/tide_gauges/lowestoft-p024-uk-bodc'

**Comment by katavouta** [comment]
@davbyr again in the Tidegauge example: https://british-oceanographic-data-centre.github.io/COAsT/docs/examples/tidegauge/

the following  lines do not work for me:
date0 = datetime.datetime(2007,1,10)
date1 = datetime.datetime(2007,1,12)
tidegauge = coast.Tidegauge(fn_tidegauge, date_start = date0, date_end = date1)

I get error:
File "/tmp/ipykernel_237908/33367625.py", line 3, in <cell line: 3>
    tidegauge = coast.Tidegauge(fn_tidegauge, date_start = date0, date_end = date1)

TypeError: __init__() got an unexpected keyword argument 'date_start'

**Comment by katavouta** [comment]
@anwiseNOCL  tested the countours example (https://british-oceanographic-data-centre.github.io/COAsT/docs/examples/contour/) and it works great for me so I will tick it (please untick it if you think there is any problem

**Comment by katavouta** [comment]
@anwiseNOCL  tested the transects example (https://british-oceanographic-data-centre.github.io/COAsT/docs/examples/transect/) and it works great for me, so I will tick it (please untick if you think there is an issue)

**Comment by katavouta** [comment]
I made the climatology work so in the example wiki instead of:

# Optional (This specifies an output file path.)
fn_out = "/path/to/outputfile.nc" 
# String is appended to "time." to create a valid xarray time period. (i.e. time.season, time.month...)
climatology_frequency = "month" 

clim = coast.Climatology()

# Not writing output to file:
clim_mean = clim.make_climatology(nemo, climatology_frequency)
# Writing output to file (may require a large amount of memory.)
clim_mean = clim.make_climatology(nemo, climatology_frequency, fn_out=fn_out)

**You have to put:**
fn_out = "/path/to/outputfile.nc" 
# String is appended to "time." to create a valid xarray time period. (i.e. time.season, time.month...)
climatology_frequency = "month" 

clim = coast.Climatology()

# Not writing output to file:
clim_mean = clim.make_climatology(nemo[['temperature','ssh']], climatology_frequency)

# Writing output to file (may require a large amount of memory.)
clim_mean = clim.make_climatology(nemo[['temperature','ssh']], climatology_frequency, fn_out=fn_out)

**Comment by katavouta** [comment]
just because the above ticket looks ugly is just the two commands that need to be updated as:

clim_mean = clim.make_climatology(nemo[['temperature','ssh']], climatology_frequency)
clim_mean = clim.make_climatology(nemo[['temperature','ssh']], climatology_frequency, fn_out=fn_out)
