### ISSUE TITLE
Rebundle config files into static master zip

### ISSUE THREAD

**Issue by jpolton** [British-Oceanographic-Data-Centre/COAsT#416]
Following the docs: https://british-oceanographic-data-centre.github.io/COAsT/docs/getting-started/#example-configuration-files
target: https://github.com/British-Oceanographic-Data-Centre/COAsT/archive/refs/heads/master.zip 

example_altimetry.json
example_argos.json
example_glider_ego.json
example_glider_ego2.json
example_gridded.json
example_indexed.json
example_nemo_grid_u.json
example_nemo_grid_v.json
example_nemo_grid_w.json
example_oceanparcels.json
example_tidegauge.json
example_en4_profiles.json
example_nemo_grid_t.json
example_nemo_grid_f.json
example_cmems_grid_t.json
example_cmems_grid_uv.json
example_nemo_bgc.json
example_wod_profiles.json

AC:
Ensure all the json files are on the Develop branch

**Comment by thogar-computer** [comment]
Need to make sure that these files are on the erddap server here

https://linkedsystems.uk/erddap/files/COAsT_example_files/

**Comment by thogar-computer** [comment]
We need to make sure that we also include the following files

coast_example_domain_SEAsia.nc
coast_example_SEAsia_BGC_1990.nc
WOD_example_ragged_standard_level.nc

**Comment by jpolton** [comment]
All files present
