### ISSUE TITLE
Separate example_scripts testing from unit_testing

### ISSUE THREAD

**Issue by jpolton** [British-Oceanographic-Data-Centre/COAsT#423]
Perhaps:

* unit_testing is a requirement for committing to develop
* example_scripts testing is a requirements for committing to `master`

Example scripts have two (three?) types:
* Can be run with `example_files`
* Can not be run with `example_files`
* No data dependency?

Story: Seeking advice on how to structure the workflow that ends up with working code on master.

**Aug Update** We are moving example_scripts/*py to notebooks.ipynb   Is there a workflow to verify these still work before a push to master?

**Comment by lukegorman** [comment]
maybe pick this up tomorrow

**Comment by jpolton** [comment]
example_scripts are physically removed from unit_testing
example_scripts/notebooks are tested during the documentation build.
Component functionality is tested during component testing.
A new issue to map notebook testing GitAction from COAsT-site to COAsT:
