### ISSUE TITLE
add sub folders within the coast package

### ISSUE THREAD

**Issue by jpolton** [British-Oceanographic-Data-Centre/COAsT#440]
(From JIRA: BODCDMSYS-3715)
As a developer I want the coast package structure to help make usage simpler for new users. 

This ticket is to add sub folder(s) to the current package. the attached image give a idea of what is being asked for. This ticket will also update all code including unit tests and example scripts to make use of the new structure. some working might also be require to make use all folders within coast are picked up for packaging. 

Notes 
****** 
The attached image (Coast-v2.0.0.rc1) shows current plan for the new framework structure (in blue). That being being a root coast folder, containing two sub folder analysis and core. Analysis would contain only 'science' classes and utils. Core would contain a single folder called data (maybe a better name needed here) this data folder would contain all classses to do with input files i.e models output and observations. 

The section in red (and yellow) would be furture work if require based on how users interact with the code base. 

Within the analysis folder there is the pontinal to have different groupings of class by style. I.E is it a scince object (with method per data class - Gridded, glider, Track) or is it a utility (python file with a collection of losse related static methods) 

this part has not be fully worked out and could form another ticket in time permits.

**Comment by thogar-computer** [comment]
see https://github.com/British-Oceanographic-Data-Centre/COAsT/issues/442 as main ticket
