### ISSUE TITLE
Example scripts folder (accessing files and other things)

### ISSUE THREAD

**Issue by jpolton** [British-Oceanographic-Data-Centre/COAsT#445]
there is a folder of tested scripts that forms the basis of a teach-yourself COAsT with some worked examples. Files ending in _tutorial.py are more polished. 

Other scripts were knocked together to get someone started with a real world use case. The above config example was me getting the code to work with the new json file structure (that I don't yet fully understand). 

How should the path/file names appear? Since these are not exposed in the conda install it is more OK for the path names to be specific and not working for everyone in the world. Especially if "For example" comment was added. 

Ideally these paths would be updated to access data only available from the ERDAP server, but we were a bit lazy with prepping data for it. I think that that is the appropriate direction of travel though.

Comment:

The content of example_scripts has some overlap with the www Examples documentation. https://british-oceanographic-data-centre.github.io/COAsT/docs/examples/ 

We were working towards harmonising these. 

Perhaps maintaining example_scripts and ipynb notebooks that were mirrored, or converted and exported, to the www.

**Comment by lukegorman** [comment]
@jpolton is this completed with the addition of jupyter notebooks and the action that converts the to MD on the site?
