### ISSUE TITLE
Create python notebook for example code files

### ISSUE THREAD

**Issue by thogar-computer** [British-Oceanographic-Data-Centre/COAsT#457]
There are example code files within coast that would benefit from being turned into python notebooks. 

https://british-oceanographic-data-centre.github.io/COAsT/docs/examples/

see https://github.com/British-Oceanographic-Data-Centre/COAsT/issues/445 for a wider context of the usefulness of notebooks

there are 24 python files within the examples script folder
https://github.com/British-Oceanographic-Data-Centre/COAsT/tree/master/example_scripts

**Comment by thogar-computer** [comment]
@jpolton Can we have a priority list scripts to convert

**Comment by jpolton** [comment]
Here is a typical one: `example_scripts/tidegauge_validation/tidegauge_validation_tutorial.py` found at https://github.com/British-Oceanographic-Data-Centre/COAsT/blob/develop/example_scripts/tidegauge_validation/tidegauge_validation_tutorial.py

**Comment by jpolton** [comment]
@lukegorman @roje-bodc The above python example is a more mature example script where it is clearer where the notebook breaks would go. Files in the tidegauge_validation and profile_validation directories are tidier because they have been iterated many times. I'd start with these as exemplars.
