### ISSUE TITLE
Transport across a transect. NEMO class method

### ISSUE THREAD

**Issue by anwiseNOCL** [British-Oceanographic-Data-Centre/COAsT#48]
A method of the NEMO class (because calculations depend on the model used).

This method will return the transports of the flow across the transect AB between two points A and B. This can either be depth integrated, as a function of vertical level, or as a function of depth.

AC:
Input, two points
output, transports across transect connecting the two points.

**Comment by jpolton** [comment]
@anwiseNOCL My code snippet for plotting a transect w/o interpolation, where dom_nwes and sci_nwes are DOMAIN and NEMO objects:

```
# Extract a depth section of data
yi,xi,line_len = dom_nwes.transect_indices([51,3],[62,3], grid_ref='t')
# Extract the variable
data_sec = sci_nwes.get_subset_as_xarray("thetao",xi,yi)
# Extract the depth section
dep_sec = xr.DataArray( dom_nwes.get_subset_as_xarray("e3t_0",xi,yi).
                         cumsum( dim='z_dim' ).squeeze() ) 
# Extract the lat section
_, lat_sec = xr.broadcast( data_sec, dom_nwes.get_subset_as_xarray("gphit",xi,yi).squeeze() )

#%%

plt.pcolormesh(  lat_sec, dep_sec, data_sec)
plt.title('section')
plt.xlim([51,62])
#plt.clim([0, 50])
plt.gca().invert_yaxis()
plt.colorbar()
plt.show()
```
