### ISSUE TITLE
unit_testing errors

### ISSUE THREAD

**Issue by jpolton** [British-Oceanographic-Data-Centre/COAsT#483]
3 errors in the unit_testing related to harmonic analysis.

AC:
`run unit_testing/unit_test.py` without errors

**Comment by lukegorman** [comment]
Unit tests:
=========================================================================== short test summary info ============================================================================
FAILED unit_testing/test_TEMPLATE.py::test_TEMPLATE::test_bad_method - AssertionError: False is not true : 1 does not equal 2
FAILED unit_testing/test_TEMPLATE.py::test_TEMPLATE::test_with_subtests - AssertionError: 1 != 50000000 within 7 places (49999999 difference) : 0 is not almost equal to 5000...
FAILED unit_testing/test_bgc_gridded_initialisation.py::test_bgc_gridded_initialisation::test_gridded_load_bgc_data - FileNotFoundError: [Errno 2] No such file or directory:...
FAILED unit_testing/test_bgc_gridded_initialisation.py::test_bgc_gridded_initialisation::test_gridded_load_bgc_data_and_domain - FileNotFoundError: [Errno 2] No such file or...
FAILED unit_testing/test_bgc_gridded_initialisation.py::test_bgc_gridded_initialisation::test_gridded_load_bgc_dimensions_correctly_renamed - FileNotFoundError: [Errno 2] No...
FAILED unit_testing/test_bgc_gridded_initialisation.py::test_bgc_gridded_initialisation::test_gridded_load_bgc_domain_only - FileNotFoundError: [Errno 2] No such file or dir...
FAILED unit_testing/test_bgc_gridded_initialisation.py::test_bgc_gridded_initialisation::test_gridded_load_bgc_variables_correctly_renamed - FileNotFoundError: [Errno 2] No ...
FAILED unit_testing/test_example_scripts.py::test_example_scripts::test_tidegauge_validation_tutorial - FileNotFoundError: [Errno 2] No such file or directory: b'/home/llama...
FAILED unit_testing/test_index_classes_load_datasets.py::test_load_altimetry_no_config - FileNotFoundError: [Errno 2] No such file or directory: b'/home/llama/noc/COAsT/exam...
FAILED unit_testing/test_index_classes_load_datasets.py::test_load_altimetry_config - FileNotFoundError: [Errno 2] No such file or directory: b'/home/llama/noc/COAsT/example...
FAILED unit_testing/test_index_classes_load_datasets.py::test_load_profile_no_config - TypeError: __init__() got an unexpected keyword argument 'file_path'
FAILED unit_testing/test_index_classes_load_datasets.py::test_load_profile_config - TypeError: __init__() got an unexpected keyword argument 'file_path'
FAILED unit_testing/test_index_classes_load_datasets.py::test_load_wod_config - FileNotFoundError: [Errno 2] No such file or directory: b'/home/llama/noc/COAsT/example_files...
FAILED unit_testing/test_index_classes_load_datasets.py::test_load_glider_no_config - FileNotFoundError: [Errno 2] No such file or directory: b'/home/llama/noc/COAsT/example...
FAILED unit_testing/test_index_classes_load_datasets.py::test_load_glider_config - FileNotFoundError: [Errno 2] No such file or directory: b'/home/llama/noc/COAsT/example_fi...
FAILED unit_testing/test_index_classes_load_datasets.py::test_load_argos_no_config - FileNotFoundError: [Errno 2] No such file or directory: './example_files/ARGOS.CSV'
FAILED unit_testing/test_index_classes_load_datasets.py::test_load_argos_config - FileNotFoundError: [Errno 2] No such file or directory: './example_files/ARGOS.CSV'
FAILED unit_testing/test_index_classes_load_datasets.py::test_load_oceanparcels_no_config - FileNotFoundError: [Errno 2] No such file or directory: b'/home/llama/noc/COAsT/e...
FAILED unit_testing/test_index_classes_load_datasets.py::test_load_oceanparcels_config - FileNotFoundError: [Errno 2] No such file or directory: b'/home/llama/noc/COAsT/exam...
FAILED unit_testing/test_index_classes_load_datasets.py::test_load_tidegauge_no_config - TypeError: __init__() got an unexpected keyword argument 'file_path'
FAILED unit_testing/test_index_classes_load_datasets.py::test_load_tidegauge_config - TypeError: __init__() got an unexpected keyword argument 'file_path'
FAILED unit_testing/test_index_classes_load_datasets.py::test_load_tidegauge_multiple_config - AttributeError: type object 'Tidegauge' has no attribute 'create_multiple_tide...
FAILED unit_testing/test_profile_methods.py::test_profile_methods::test_compare_processed_profile_with_model - FileNotFoundError: [Errno 2] No such file or directory: b'/hom...
FAILED unit_testing/test_profile_methods.py::test_profile_methods::test_load_process_and_compare_profile_data - FileNotFoundError: [Errno 2] No such file or directory: b'/ho...
FAILED unit_testing/test_tidegauge_methods.py::test_tidegauge_analysis::test_harmonic_analysis_utide - AssertionError: False is not true : check1
FAILED unit_testing/test_wod_read_data.py::test_wod_read_data::test_load_wod - FileNotFoundError: [Errno 2] No such file or directory: b'/home/llama/noc/COAsT/example_files/...
FAILED unit_testing/test_wod_read_data.py::test_wod_read_data::test_reshape_wod - FileNotFoundError: [Errno 2] No such file or directory: b'/home/llama/noc/COAsT/example_fil...
FAILED unit_testing/unit_test.py::test_TEMPLATE::test_bad_method - AssertionError: False is not true : 1 does not equal 2
FAILED unit_testing/unit_test.py::test_TEMPLATE::test_with_subtests - AssertionError: 1 != 50000000 within 7 places (49999999 difference) : 0 is not almost equal to 50000000
FAILED unit_testing/unit_test.py::test_tidegauge_analysis::test_harmonic_analysis_utide - AssertionError: False is not true : check1
FAILED unit_testing/unit_test.py::test_profile_methods::test_compare_processed_profile_with_model - FileNotFoundError: [Errno 2] No such file or directory: b'/home/llama/noc...
FAILED unit_testing/unit_test.py::test_profile_methods::test_load_process_and_compare_profile_data - FileNotFoundError: [Errno 2] No such file or directory: b'/home/llama/no...
FAILED unit_testing/unit_test.py::test_wod_read_data::test_load_wod - FileNotFoundError: [Errno 2] No such file or directory: b'/home/llama/noc/COAsT/example_files/WOD_examp...
FAILED unit_testing/unit_test.py::test_wod_read_data::test_reshape_wod - FileNotFoundError: [Errno 2] No such file or directory: b'/home/llama/noc/COAsT/example_files/WOD_ex...
FAILED unit_testing/unit_test.py::test_example_scripts::test_tidegauge_validation_tutorial - FileNotFoundError: [Errno 2] No such file or directory: b'/home/llama/noc/COAsT/...
FAILED unit_testing/unit_test.py::test_bgc_gridded_initialisation::test_gridded_load_bgc_data - FileNotFoundError: [Errno 2] No such file or directory: b'/home/llama/noc/COA...
FAILED unit_testing/unit_test.py::test_bgc_gridded_initialisation::test_gridded_load_bgc_data_and_domain - FileNotFoundError: [Errno 2] No such file or directory: b'/home/ll...
FAILED unit_testing/unit_test.py::test_bgc_gridded_initialisation::test_gridded_load_bgc_dimensions_correctly_renamed - FileNotFoundError: [Errno 2] No such file or director...
FAILED unit_testing/unit_test.py::test_bgc_gridded_initialisation::test_gridded_load_bgc_domain_only - FileNotFoundError: [Errno 2] No such file or directory: b'/home/llama/...
FAILED unit_testing/unit_test.py::test_bgc_gridded_initialisation::test_gridded_load_bgc_variables_correctly_renamed - FileNotFoundError: [Errno 2] No such file or directory...
==================================================== 40 failed, 166 passed, 1 skipped, 1150 warnings in 1016.47s (0:16:56) =====================================================

**Comment by jpolton** [comment]
@lukegorman Have you [downloaded example files](https://british-oceanographic-data-centre.github.io/COAsT/docs/getting-started/#obtaining-example-files)?
