### ISSUE TITLE
Add note book images to site

### ISSUE THREAD

**Issue by lukegorman** [British-Oceanographic-Data-Centre/COAsT#526]
Can images be included in the ipynb files that will be rendered on the www docs?

**Comment by lukegorman** [comment]
Timebox it with 2 days.
Present recommendation, if any, at end.

**Comment by thogar-computer** [comment]
So a very quick read of the nbconvert program lead me too 
https://nbconvert.readthedocs.io/en/latest/execute_api.html
and 
https://nbconvert.readthedocs.io/en/latest/usage.html#convert-markdown

interestingly it mention that images are outputted as .png  files in a folder

I am not sure if we can combined the two to form something like
``` shell
jupyter nbconvert --to notebook --execute mynotebook.ipynb # new notebook build from the output of given notebook
jupyter nbconvert --to markdown  mynotebook.nbconvert.ipynb # convert new notebook which should contain images
del mynotebook.nbconvert.ipynb # clear up unrequired notebook
```

**Comment by thogar-computer** [comment]
@lukegorman  @roje-bodc

**Comment by lukegorman** [comment]
cool we ran this on a notebook that we have data for and it works. one question is can hugo find a the assets where they are located (in a subdir by the notebooks)

**Comment by lukegorman** [comment]
the plan atm. is update the to_md script to include the above and have jeff run it with all necessary data available....

**Comment by roje-bodc** [comment]
We have managed to run the altimetry notebook within a docker image that we have created and then convert this to markdown :

![Image](https://user-images.githubusercontent.com/64262641/189158714-18f94f5f-e2d8-43d7-a89b-01f3a791cafd.png)

**Comment by thogar-computer** [comment]
I have tested this locally, 

there are a few edits that will need to be done to the files to make the process easier

**Comment by thogar-computer** [comment]
the main action is not to print out xarray objects into the notebooks bu default

**Comment by thogar-computer** [comment]
work has been done on both the coast site and coast repos 

there is a new structure in the coast site for markdown files
