### ISSUE TITLE
change name of directory notebook to notebook_tutorials

### ISSUE THREAD

**Issue by jpolton** [British-Oceanographic-Data-Centre/COAsT#551]
In COAsT:example_scripts/notebooks

This is where all the notebooks live that get rendered on the docsy site.
They are all the tutorials.

They are a "don't touch unless you know what you are doing" part of this folder.

"notebooks" --> "notebooks_tutorials" might better signify that importance of these entries

**Comment by roje-bodc** [comment]
https://github.com/British-Oceanographic-Data-Centre/COAsT-site/pull/89

**Comment by roje-bodc** [comment]
https://github.com/British-Oceanographic-Data-Centre/COAsT/pull/630

**Comment by roje-bodc** [comment]
Changes merged into coast site repo. Just need to merge changes into the coast repo now.

**Comment by roje-bodc** [comment]
The coast side of this ticket is in develop.
The coast-site side is merged all the way through to master.
