### ISSUE TITLE
Issue with HDF5 libraries

### ISSUE THREAD

**Issue by jpolton** [British-Oceanographic-Data-Centre/COAsT#559]
New dependency files gives rise to inconsistency in HDF5 library (probably) that leads to nasties in the unit_testing.

Triggered e.g. by
```
test_gridded_load_multiple (test_gridded_initialisation.test_gridded_initialisation) ... HDF5-DIAG: Error detected in HDF5 (1.12.2) thread 1:
  #000: H5A.c line 528 in H5Aopen_by_name(): can't open attribute
    major: Attribute
    minor: Can't open object
  #001: H5VLcallback.c line 1091 in H5VL_attr_open(): attribute open failed
    major: Virtual Object Layer
    minor: Can't open object
  #002: H5VLcallback.c line 1058 in H5VL__attr_open(): attribute open failed
    major: Virtual Object Layer
    minor: Can't open object
...
```

Solution: fix dependency versions to ones that used to work

**Comment by jpolton** [comment]
Try fixing dependencies for known releases.

```
- pip:
    - numpy==1.22.3
    - dask==2022.3.0
    - dask[complete]==2022.3.0
    - xarray==2022.3.0
    - matplotlib>=3.5.3
    - netCDF4==1.5.8
```

**Comment by ledm** [comment]
I'm seeing this issue as well. I suspect it's related to leaving a resource open (#581), which explains why my code runs the first time fine, then I see this bug if I run it again afterwards.
```

HDF5-DIAG: Error detected in HDF5 (1.12.2) thread 11:
  #000: H5A.c line 528 in H5Aopen_by_name(): can't open attribute
    major: Attribute
    minor: Can't open object
  #001: H5VLcallback.c line 1091 in H5VL_attr_open(): attribute open failed
    major: Virtual Object Layer
    minor: Can't open object
  #002: H5VLcallback.c line 1058 in H5VL__attr_open(): attribute open failed
    major: Virtual Object Layer
    minor: Can't open object
  #003: H5VLnative_attr.c line 130 in H5VL__native_attr_open(): can't open attribute
    major: Attribute
    minor: Can't open object
  #004: H5Aint.c line 545 in H5A__open_by_name(): unable to load attribute info from object header
    major: Attribute
    minor: Unable to initialize object
  #005: H5Oattribute.c line 476 in H5O__attr_open_by_name(): can't open attribute
    major: Attribute
    minor: Can't open object
  #006: H5Adense.c line 394 in H5A__dense_open(): can't locate attribute in name index
    major: Attribute
    minor: Object not found
HDF5-DIAG: Error detected in HDF5 (1.12.2) thread 11:
  #000: H5A.c line 528 in H5Aopen_by_name(): can't open attribute
    major: Attribute
    minor: Can't open object
  #001: H5VLcallback.c line 1091 in H5VL_attr_open(): attribute open failed
    major: Virtual Object Layer
    minor: Can't open object
  #002: H5VLcallback.c line 1058 in H5VL__attr_open(): attribute open failed
    major: Virtual Object Layer
    minor: Can't open object
  #003: H5VLnative_attr.c line 130 in H5VL__native_attr_open(): can't open attribute
    major: Attribute
    minor: Can't open object
  #004: H5Aint.c line 545 in H5A__open_by_name(): unable to load attribute info from object header
    major: Attribute
    minor: Unable to initialize object
  #005: H5Oattribute.c line 476 in H5O__attr_open_by_name(): can't open attribute
    major: Attribute
    minor: Can't open object
  #006: H5Adense.c line 394 in H5A__dense_open(): can't locate attribute in name index
    major: Attribute
    minor: Object not found
HDF5-DIAG: Error detected in HDF5 (1.12.2) thread 11:
  #000: H5A.c line 528 in H5Aopen_by_name(): can't open attribute
    major: Attribute
    minor: Can't open object
  #001: H5VLcallback.c line 1091 in H5VL_attr_open(): attribute open failed
    major: Virtual Object Layer
    minor: Can't open object
  #002: H5VLcallback.c line 1058 in H5VL__attr_open(): attribute open failed
    major: Virtual Object Layer
    minor: Can't open object
  #003: H5VLnative_attr.c line 130 in H5VL__native_attr_open(): can't open attribute
    major: Attribute
    minor: Can't open object
  #004: H5Aint.c line 545 in H5A__open_by_name(): unable to load attribute info from object header
    major: Attribute
    minor: Unable to initialize object
  #005: H5Oattribute.c line 476 in H5O__attr_open_by_name(): can't open attribute
    major: Attribute
    minor: Can't open object
  #006: H5Adense.c line 394 in H5A__dense_open(): can't locate attribute in name index
    major: Attribute
    minor: Object not found
HDF5-DIAG: Error detected in HDF5 (1.12.2) thread 11:
  #000: H5A.c line 528 in H5Aopen_by_name(): can't open attribute
    major: Attribute
    minor: Can't open object
  #001: H5VLcallback.c line 1091 in H5VL_attr_open(): attribute open failed
    major: Virtual Object Layer
    minor: Can't open object
  #002: H5VLcallback.c line 1058 in H5VL__attr_open(): attribute open failed
    major: Virtual Object Layer
    minor: Can't open object
  #003: H5VLnative_attr.c line 130 in H5VL__native_attr_open(): can't open attribute
    major: Attribute
    minor: Can't open object
  #004: H5Aint.c line 545 in H5A__open_by_name(): unable to load attribute info from object header
    major: Attribute
    minor: Unable to initialize object
  #005: H5Oattribute.c line 476 in H5O__attr_open_by_name(): can't open attribute
    major: Attribute
    minor: Can't open object
  #006: H5Adense.c line 394 in H5A__dense_open(): can't locate attribute in name index
    major: Attribute
    minor: Object not found
HDF5-DIAG: Error detected in HDF5 (1.12.2) thread 11:
  #000: H5A.c line 528 in H5Aopen_by_name(): can't open attribute
    major: Attribute
    minor: Can't open object
  #001: H5VLcallback.c line 1091 in H5VL_attr_open(): attribute open failed
    major: Virtual Object Layer
    minor: Can't open object
  #002: H5VLcallback.c line 1058 in H5VL__attr_open(): attribute open failed
    major: Virtual Object Layer
    minor: Can't open object
  #003: H5VLnative_attr.c line 130 in H5VL__native_attr_open(): can't open attribute
    major: Attribute
    minor: Can't open object
  #004: H5Aint.c line 545 in H5A__open_by_name(): unable to load attribute info from object header
    major: Attribute
    minor: Unable to initialize object
  #005: H5Oattribute.c line 476 in H5O__attr_open_by_name(): can't open attribute
    major: Attribute
    minor: Can't open object
  #006: H5Adense.c line 394 in H5A__dense_open(): can't locate attribute in name index
    major: Attribute
    minor: Object not found
HDF5-DIAG: Error detected in HDF5 (1.12.2) thread 11:
  #000: H5A.c line 528 in H5Aopen_by_name(): can't open attribute
    major: Attribute
    minor: Can't open object
  #001: H5VLcallback.c line 1091 in H5VL_attr_open(): attribute open failed
    major: Virtual Object Layer
    minor: Can't open object
  #002: H5VLcallback.c line 1058 in H5VL__attr_open(): attribute open failed
    major: Virtual Object Layer
    minor: Can't open object
  #003: H5VLnative_attr.c line 130 in H5VL__native_attr_open(): can't open attribute
    major: Attribute
    minor: Can't open object
  #004: H5Aint.c line 545 in H5A__open_by_name(): unable to load attribute info from object header
    major: Attribute
    minor: Unable to initialize object
  #005: H5Oattribute.c line 476 in H5O__attr_open_by_name(): can't open attribute
    major: Attribute
    minor: Can't open object
  #006: H5Adense.c line 394 in H5A__dense_open(): can't locate attribute in name index
    major: Attribute
    minor: Object not found
In [1]:

In [1]:

In [1]:


HDF5: infinite loop closing library
      L,D_top,G_top,T_top,F,P,P,Z,FD,VL,VL,PL,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E
```
This last error led me to: 
https://forum.hdfgroup.org/t/hdf5-infinite-loop-closing-library-v1-10-6/8468

**Comment by jpolton** [comment]
> I'm seeing this issue as well. I suspect it's related to leaving a resource open (#581), which explains why my code runs the first time fine, then I see this bug if I run it again afterwards.
> 
> ```
> 
> HDF5-DIAG: Error detected in HDF5 (1.12.2) thread 11:
>   #000: H5A.c line 528 in H5Aopen_by_name(): can't open attribute
>     major: Attribute
>     minor: Can't open object
>   #001: H5VLcallback.c line 1091 in H5VL_attr_open(): attribute open failed
>     major: Virtual Object Layer
>     minor: Can't open object
>   #002: H5VLcallback.c line 1058 in H5VL__attr_open(): attribute open failed
>     major: Virtual Object Layer
>     minor: Can't open object
>   #003: H5VLnative_attr.c line 130 in H5VL__native_attr_open(): can't open attribute
>     major: Attribute
>     minor: Can't open object
>   #004: H5Aint.c line 545 in H5A__open_by_name(): unable to load attribute info from object header
>     major: Attribute
>     minor: Unable to initialize object
>   #005: H5Oattribute.c line 476 in H5O__attr_open_by_name(): can't open attribute
>     major: Attribute
>     minor: Can't open object
>   #006: H5Adense.c line 394 in H5A__dense_open(): can't locate attribute in name index
>     major: Attribute
>     minor: Object not found
> HDF5-DIAG: Error detected in HDF5 (1.12.2) thread 11:
>   #000: H5A.c line 528 in H5Aopen_by_name(): can't open attribute
>     major: Attribute
>     minor: Can't open object
>   #001: H5VLcallback.c line 1091 in H5VL_attr_open(): attribute open failed
>     major: Virtual Object Layer
>     minor: Can't open object
>   #002: H5VLcallback.c line 1058 in H5VL__attr_open(): attribute open failed
>     major: Virtual Object Layer
>     minor: Can't open object
>   #003: H5VLnative_attr.c line 130 in H5VL__native_attr_open(): can't open attribute
>     major: Attribute
>     minor: Can't open object
>   #004: H5Aint.c line 545 in H5A__open_by_name(): unable to load attribute info from object header
>     major: Attribute
>     minor: Unable to initialize object
>   #005: H5Oattribute.c line 476 in H5O__attr_open_by_name(): can't open attribute
>     major: Attribute
>     minor: Can't open object
>   #006: H5Adense.c line 394 in H5A__dense_open(): can't locate attribute in name index
>     major: Attribute
>     minor: Object not found
> HDF5-DIAG: Error detected in HDF5 (1.12.2) thread 11:
>   #000: H5A.c line 528 in H5Aopen_by_name(): can't open attribute
>     major: Attribute
>     minor: Can't open object
>   #001: H5VLcallback.c line 1091 in H5VL_attr_open(): attribute open failed
>     major: Virtual Object Layer
>     minor: Can't open object
>   #002: H5VLcallback.c line 1058 in H5VL__attr_open(): attribute open failed
>     major: Virtual Object Layer
>     minor: Can't open object
>   #003: H5VLnative_attr.c line 130 in H5VL__native_attr_open(): can't open attribute
>     major: Attribute
>     minor: Can't open object
>   #004: H5Aint.c line 545 in H5A__open_by_name(): unable to load attribute info from object header
>     major: Attribute
>     minor: Unable to initialize object
>   #005: H5Oattribute.c line 476 in H5O__attr_open_by_name(): can't open attribute
>     major: Attribute
>     minor: Can't open object
>   #006: H5Adense.c line 394 in H5A__dense_open(): can't locate attribute in name index
>     major: Attribute
>     minor: Object not found
> HDF5-DIAG: Error detected in HDF5 (1.12.2) thread 11:
>   #000: H5A.c line 528 in H5Aopen_by_name(): can't open attribute
>     major: Attribute
>     minor: Can't open object
>   #001: H5VLcallback.c line 1091 in H5VL_attr_open(): attribute open failed
>     major: Virtual Object Layer
>     minor: Can't open object
>   #002: H5VLcallback.c line 1058 in H5VL__attr_open(): attribute open failed
>     major: Virtual Object Layer
>     minor: Can't open object
>   #003: H5VLnative_attr.c line 130 in H5VL__native_attr_open(): can't open attribute
>     major: Attribute
>     minor: Can't open object
>   #004: H5Aint.c line 545 in H5A__open_by_name(): unable to load attribute info from object header
>     major: Attribute
>     minor: Unable to initialize object
>   #005: H5Oattribute.c line 476 in H5O__attr_open_by_name(): can't open attribute
>     major: Attribute
>     minor: Can't open object
>   #006: H5Adense.c line 394 in H5A__dense_open(): can't locate attribute in name index
>     major: Attribute
>     minor: Object not found
> HDF5-DIAG: Error detected in HDF5 (1.12.2) thread 11:
>   #000: H5A.c line 528 in H5Aopen_by_name(): can't open attribute
>     major: Attribute
>     minor: Can't open object
>   #001: H5VLcallback.c line 1091 in H5VL_attr_open(): attribute open failed
>     major: Virtual Object Layer
>     minor: Can't open object
>   #002: H5VLcallback.c line 1058 in H5VL__attr_open(): attribute open failed
>     major: Virtual Object Layer
>     minor: Can't open object
>   #003: H5VLnative_attr.c line 130 in H5VL__native_attr_open(): can't open attribute
>     major: Attribute
>     minor: Can't open object
>   #004: H5Aint.c line 545 in H5A__open_by_name(): unable to load attribute info from object header
>     major: Attribute
>     minor: Unable to initialize object
>   #005: H5Oattribute.c line 476 in H5O__attr_open_by_name(): can't open attribute
>     major: Attribute
>     minor: Can't open object
>   #006: H5Adense.c line 394 in H5A__dense_open(): can't locate attribute in name index
>     major: Attribute
>     minor: Object not found
> HDF5-DIAG: Error detected in HDF5 (1.12.2) thread 11:
>   #000: H5A.c line 528 in H5Aopen_by_name(): can't open attribute
>     major: Attribute
>     minor: Can't open object
>   #001: H5VLcallback.c line 1091 in H5VL_attr_open(): attribute open failed
>     major: Virtual Object Layer
>     minor: Can't open object
>   #002: H5VLcallback.c line 1058 in H5VL__attr_open(): attribute open failed
>     major: Virtual Object Layer
>     minor: Can't open object
>   #003: H5VLnative_attr.c line 130 in H5VL__native_attr_open(): can't open attribute
>     major: Attribute
>     minor: Can't open object
>   #004: H5Aint.c line 545 in H5A__open_by_name(): unable to load attribute info from object header
>     major: Attribute
>     minor: Unable to initialize object
>   #005: H5Oattribute.c line 476 in H5O__attr_open_by_name(): can't open attribute
>     major: Attribute
>     minor: Can't open object
>   #006: H5Adense.c line 394 in H5A__dense_open(): can't locate attribute in name index
>     major: Attribute
>     minor: Object not found
> In [1]:
> 
> In [1]:
> 
> In [1]:
> 
> 
> HDF5: infinite loop closing library
>       L,D_top,G_top,T_top,F,P,P,Z,FD,VL,VL,PL,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E
> ```
> 
> This last error led me to: https://forum.hdfgroup.org/t/hdf5-infinite-loop-closing-library-v1-10-6/8468 Which isn't super useful, but does point out that infinite loop closing library may be linked to not closing files properly.

The ticket and PR did indeed sort the issue and alleviate the constraints on dask and xarray versions

```
   - pip:
     - numpy==1.22.3
-    - dask==2022.3.0
-    - dask[complete]==2022.3.0
-    - xarray==2022.3.0
+    - dask>=2022.3.0
+    - dask[complete]>=2022.3.0
+    - xarray>=2022.3.0
     - matplotlib>=3.5.3
```
Now works
