### ISSUE TITLE
[NEW FEATURE] Fix for potential problem with dangling opened files

### ISSUE THREAD

**Issue by ledm** [British-Oceanographic-Data-Centre/COAsT#581]
### Is there an existing request for this?

- [X] I have searched the existing request

### Desired Feature

In `coast/data/coast.py`, single and multiple datasets are openned using:
```
self.dataset = xr.open_dataset(file, chunks=chunks)
```
and 
```
self.dataset = xr.open_mfdataset(directory_to_files, chunks=chunks, parallel=True, combine="by_coords")
```

The problem with this method is that it is easy to forget to close the files, and they can sometimes be left open.

The more pythonic way to do this is with the "with as" framework:
```
        with xr.open_dataset(file, chunks=chunks) as xrfile:
            self.dataset = xrfile
```
and
```
        with xr.open_mfdataset(directory_to_files, chunks=chunks, parallel=True, combine="by_coords") as xrfiles:
            self.dataset = xrfiles
```
This change should ensure that the resource is cleaned up correctly when it finishes running, even if exceptions are thrown. (Tip courtesy of professional python dev @valeriupredoi https://github.com/valeriupredoi )

### Justification

This is a stabililty improvement.

### User Workflow

No changes required from users.

### Anything else?

https://docs.python.org/3/reference/compound_stmts.html#with

**Comment by ledm** [comment]
I have a fix for this, but I don't have permission to contribute to the code yet.

**Comment by valeriupredoi** [comment]
Hi @ledm - nice fix! You can try opening a pull request directly here via a fork of this repo - so you fork COAsT in a personal fork, create a branch with the changes you propose, then open a PR here from your personal forked branch, see what the devs here say :beer:

**Comment by thogar-computer** [comment]
Afternoon, @ledm 

@valeriupredoi is correct, we would prefer a forked pull request. 

The fork can be done, via this link -> https://github.com/British-Oceanographic-Data-Centre/COAsT/fork

if you then create a branch, ideally named something like `#581-file-closing`, you can commit all your changes into there and then open a pull request to the main coast repo.

**Comment by jpolton** [comment]
@ledm your feature is in develop and I've amended the CITATION.cff to include you. Are you happy with this? I will aim to push to master in the next week or so, to create a new release with your feature in.

**Comment by ledm** [comment]
Sure, sounds good! Credit should go to @valeriupredoi as well who suggested this edit.

**Comment by valeriupredoi** [comment]
cheers, guys! @jpolton don't worry too much about adding me to the CITATION file if it's a problem since I've not actually opened the PR and did the code changes :beer:
