### ISSUE TITLE
Tidy notebooks

### ISSUE THREAD

**Issue by jpolton** [British-Oceanographic-Data-Centre/COAsT#602]
example_scripts folders are a bit messy. It looks like some of it is not getting push to the docsy site and should be reviewed. Should it be removed altogether or added.

**Comment by thogar-computer** [comment]
everything within the runnable folder should be runnable, everything else needs to be looked at and see if it is used, if not then it needs to be deleted.

**Comment by roje-bodc** [comment]
Note that the push to the docsy site has been broken for a long time.

I have fixed this push as part of ticket: https://github.com/British-Oceanographic-Data-Centre/COAsT/issues/551

**Comment by roje-bodc** [comment]
Also as the conversion to markdown passed, this means that all of the notebooks in the runnable notebooks folder are runnable. The notebooks are executed as part of the conversion process.

**Comment by roje-bodc** [comment]
Out of the entire example scripts folder, these are the files that aren't on the docsy site:

EXAMPLE_SCRIPTS/
│   indexed_tutorial.py
│   README
│   stratification_pycnocline_diagnostics.py
│   __init__.py
│
├───configuration_gallery/
│       anchor_plots_of_nsea_wvel.py
│       blz_example_plot.py
│       seasia_dic_example_plot.py
│
└───profile_validation/
        1._analysis_preprocess_en4.ipynb
        2._analysis_extract_and_compare.ipynb
        3._analysis_extract_and_compare_single_process_tutorial.ipynb
        4._analysis_mask_means_tutorial.ipynb
        5._analysis_average_into_grid_boxes.ipynb
        analysis_extract_and_compare.py
        plot_validation_gridded_data.py
        plot_validation_gridded_data_tutorial.ipynb
        plot_validation_mask_means.ipynb
        plot_validation_mask_means.py
        plot_validation_surface_errors.ipynb
        plot_validation_surface_errors.py

**Comment by roje-bodc** [comment]
@jpolton  I've added my suggestions beside each file here:

```text

EXAMPLE_SCRIPTS/
│   indexed_tutorial.py	(Delete or convert to a notebook?)
│   README (Keep)
│   stratification_pycnocline_diagnostics.py (Delete this? There seems to be a similarly title notebook 
						'notebook_tutorials\runnable_notebooks\gridded\pycnocline_tutorial.ipynb' )
│   __init__.py	(Delete this? I don't think anyone is using this directory as a package.)
│
├───configuration_gallery/
│       anchor_plots_of_nsea_wvel.py (Convert this to a notebook?)
│       blz_example_plot.py (Convert this to a notebook?)
│       seasia_dic_example_plot.py (Convert this to a notebook?)
│
└───profile_validation/ (Not sure what these do but they are well laid out. Maybe just need a section on the docsy explaining what they are??
				Might need a opinion here to see whether these are useful or not )
        1._analysis_preprocess_en4.ipynb
        2._analysis_extract_and_compare.ipynb
        3._analysis_extract_and_compare_single_process_tutorial.ipynb
        4._analysis_mask_means_tutorial.ipynb
        5._analysis_average_into_grid_boxes.ipynb
        analysis_extract_and_compare.py
        plot_validation_gridded_data.py
        plot_validation_gridded_data_tutorial.ipynb
        plot_validation_mask_means.ipynb
        plot_validation_mask_means.py
        plot_validation_surface_errors.ipynb
        plot_validation_surface_errors.py

```

**Comment by jpolton** [comment]
`Profile_validation/` is all copied into Runnable Section "Introduction to profile class". So can be removed.

`configuration_gallery/` is not worth keeping, so can be removed.

`stratification_pycnocline_diagnostics.py` - delete

README - update (keep only 1st paragraph)

`indexed_tutorial.py` - Keep? This is a bit of a placeholder for stubs we haven't expanded? To discuss

**Comment by roje-bodc** [comment]
I've made the above changes and they are in a pull request:
https://github.com/British-Oceanographic-Data-Centre/COAsT/pull/634

I've also removed reference to the configuration gallery folder in the coast site:
https://github.com/British-Oceanographic-Data-Centre/COAsT-site/pull/94

**Comment by roje-bodc** [comment]
@jpolton  I've re-added the configuraition gallery files that we want to keep (the ones referenced in the docsy site.) So the Pull request https://github.com/British-Oceanographic-Data-Centre/COAsT/pull/634 is now okay to review.

(Not sure why is says the Amm15 file is blank, as it does exist on the branch. So just ignore that part. I think github got a bit confused since I re-added the file after deleting it.)
