### ISSUE TITLE
Unit testing guidelines: 

### ISSUE THREAD

**Issue by jpolton** [British-Oceanographic-Data-Centre/COAsT#68]
Make a doc in the repo explaining what is expected of a good unit_test for a new feature.

I.e something about handling gnarly grids

**Comment by davbyr** [comment]
@jpolton @anwiseNOCL Added a new unit_testing_guidelines.txt file to a 0068 branch. This is just a short draft document. Please take a look edit as you wish.

**Comment by jpolton** [comment]
The unit_testing_guidlines.txt should probably go in a folder `unit_testing` along with the `unit_testing.py` script. I'm going implement this suggestion and  merge my script branch into this branch (partly as an excerise).

**Comment by jpolton** [comment]
OK note the directory structure on this branch is now slightly modified for unit testing:
|
|_ coast
|     |_ ...
|
|_example_files
|    |_ ...
|
|_ unit_testing
     |_ unit_test.py
     |_ unit_testing_guidelines.txt

**Comment by jpolton** [comment]
@davbyr @anwiseNOCL - Can we objectively test plotting methods? Hmmm. 
Perhaps worth auto-plotting these methods to a gitignore folder, for voluntary inspection will suffice.
More objective methods may not be worth the effort.

**Comment by davbyr** [comment]
@jpolton @anwiseNOCL I think voluntary inspection, via saving plots to a gitignore folder as you say, is the easiest way to do it. We could always provide a set of intended plots for comparison if needed.
