### ISSUE TITLE
Can't open example netcdf files on linux machines

### ISSUE THREAD

**Issue by anwiseNOCL** [British-Oceanographic-Data-Centre/COAsT#77]
@jpolton  @davbyr 
For some reason the example data files are not opening on the livljobs machines. Works fine locally on mac. I do not understand why. I get 
"COAsT_example_data_141020.nc: NetCDF: Unknown file format"
when I try to access it with ncdump and same error when i access it in python. No probs opening other netcdf files..

Can you check if you have this problem?

**Comment by davbyr** [comment]
@anwiseNOCL Just had a go. Conda is throwing unexpected errors for me right now on livljobs just trying to create environments/install packages so haven't managed to test it in python. ncdump works fine for the most recent files though (for me). Try the files in the 0063 branch

**Comment by anwiseNOCL** [comment]
Ok that's weird. However good news is that the 0063 branch files are working on the linux machines for me so I guess no problem once that merges.

**Comment by davbyr** [comment]
OK that's good. 0063 is currently in a pull request by the way, so can be merged once approved.
