### ISSUE TITLE
Something fishy with git-lfs

### ISSUE THREAD

**Issue by jpolton** [British-Oceanographic-Data-Centre/COAsT#79]
Whenever I do ```git status``` I always get warning about the example data

E.g.
```
git status
On branch develop
Your branch is up to date with 'origin/develop'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   example_files/COAsT_example_altimetry_data.nc

```

I think that it is because the git-lfs was used, and there is a dot file somewhere saying so, but that we don't use git-lfs anymore.

Does anyone else have this issue?
A solution is probably to remove reference to git-lfs in the dot files

**Comment by jpolton** [comment]
Pointer needed resetting.
Advice from: https://github.com/git-lfs/git-lfs/issues/3787
```
(coast_env) [LIVMAP:~/GitHub/COAsT] jeff% git lfs untrack example_files/COAsT_example_altimetry_data.nc
(coast_env) [LIVMAP:~/GitHub/COAsT] jeff% git rm --cached example_files/COAsT_example_altimetry_data.nc
rm 'example_files/COAsT_example_altimetry_data.nc'
(coast_env) [LIVMAP:~/GitHub/COAsT] jeff% git add example_files/COAsT_example_altimetry_data.nc
(coast_env) [LIVMAP:~/GitHub/COAsT] jeff% git add example_files/COAsT_example_NEMO_domain.nc
(coast_env) [LIVMAP:~/GitHub/COAsT] jeff% git commit -m 'restore example_files COAsT_example_altimetry_data.nc and COAsT_example_altimetry_data.nc to git from lfs'
[0059_pycno_var 839dd7d] restore example_files COAsT_example_altimetry_data.nc and COAsT_example_altimetry_data.nc to git from lfs
```
Then push back to repo.

So far I've only done this on one of my branches: ``0059_pycno_var``

**Comment by jpolton** [comment]
@anwiseNOCL @davbyr 

I think that I am the only one using git-lfs !

If I do a hard rest to the develop branch and look for git lfs files:

```
cd 
COAsT/example_files
git lfs ls-files
```

I get nothing. I bet you get nothing too...

If I follow the above  commands sequence to reset the git-lfs pointer and then repeat the query:

```
git lfs ls-files
2241b52015 - example_files/COAsT_example_NEMO_data.nc
12350d05c3 - example_files/COAsT_example_NEMO_domain.nc
88a94f4760 - example_files/COAsT_example_altimetry_data.nc
```

If @anwiseNOCL and / or @davbyr can vertify then we have to decide what to do about this. (I think that git-lfs will create eventually  bandwidth problems. We discussed this before but it is hazy)

**Comment by anwiseNOCL** [comment]
I get...

```
(coast_dev) livljobs6 example_files $ git lfs ls-files
git: 'lfs' is not a git command. See 'git --help'.

Did you mean this?
	log
```
so i suppose i don't have it

**Comment by jpolton** [comment]
The new plan is to strip git LFS out of the repository and store data elsewhere. E.g. workflow:

1. commit & push everything
2. remove hooks

``git lfs uninstall``

3. remove lfs stuff from ``.gitattributes`` (comment out line)
4. find and remove lfs stuff on files. list lfs files using ``git lfs ls-files``
then ``run git rm --cached <file>``:

```
git rm --cached example_files/COAsT_example_NEMO_data.nc; 
git rm --cached example_files/COAsT_example_NEMO_domain.nc;
git rm --cached example_files/COAsT_example_altimetry_data.nc
```

5. Restore files. run git add for each file:

```
git add example_files/COAsT_example_NEMO_data.nc
git add example_files/COAsT_example_NEMO_domain.nc
git add example_files/COAsT_example_altimetry_data.nc
```

6. commit everything:

```
git add .gitattributes
git commit -m "un LFS files"
git push origin
```

7. check that no lfs files left:
``git lfs ls-files``
remove junk
``rm -rf .git/lfs``
you're all done
(but unlinked junk is within BitBucket Git LFS storage still)

**Comment by jpolton** [comment]
Testing removing git-lfs with two pull requests https://github.com/British-Oceanographic-Data-Centre/COAsT/pull/93 and https://github.com/British-Oceanographic-Data-Centre/COAsT/pull/95

**Comment by jpolton** [comment]
The pull requests into develop successfully removed git-lfs pointers.
