### ISSUE TITLE
Standard names for variables, axes, dimension

### ISSUE THREAD

**Issue by jpolton** [British-Oceanographic-Data-Centre/COAsT#84]
set_variables
set_dimensions
set_coordinates

They need to establish standard naming for models and observations data.
* Ideally there would be a simple automatic sweep for standard names
* User input dictionary for exotic names?

**Comment by jpolton** [comment]
I spent 1h 30 trying to fix git-lfs so I could do a new branch and commit....
Ran out of time. 

In DOMAIN.py and NEMO.py I was going to add:
```
    def set_command_dimensions(self):
        """ A method to relabel the domain dimensions for consistent
        and transparent use in this package:
            t_dim - time
            z_dim - depth
            y_dim - northish (accepting that grids can be rotated)
            x_dim - eastish (accepting that grids can be rotated)
        """
        try:
            self.dataset = self.dataset.rename_dims({'t':'t_dim'})
        except AttributeError as e:
            print(str(e))

        try:
            self.dataset = self.dataset.rename_dims({'z':'z_dim'})
        except AttributeError as e:
            print(str(e))

        try:
            self.dataset = self.dataset.rename_dims({'y':'y_dim'})
        except AttributeError as e:
            print(str(e))

        try:
            self.dataset = self.dataset.rename_dims({'x':'x_dim'})
        except AttributeError as e:
            print(str(e))
```
Though `set_dimensions` would be a better name...

Would this work for us?

**Comment by davbyr** [comment]
@jpolton I think this can work. It might be better to do it via an iteration through a mapping dictionary:

```
def set_command_dimensions(self, dim_mapping: dict=None):
    """ A method to relabel the domain dimensions for consistent
    and transparent use in this package:
        t_dim - time
        z_dim - depth
        y_dim - northish (accepting that grids can be rotated)
        x_dim - eastish (accepting that grids can be rotated)
    """
    if dim_mapping is None:
        dim_mapping = {'t':'t_dim',
                                   'z':'z_dim',
                                   'y':'y_dim',
                                   'x':'x_dim'}
    
    for key, value in dim_mapping.items():
        try:
            self.dataset = self.dataset.rename_dims({ key : value })
        except: AttributeError as e:
            print('Problem mapping ' + key + ' to ' + value)
```
The default mapping dictionary can then be defined at the top of the function (to be used when loading) or a dictionary can be supplied as an argument by the user (if manual renaming is required). Although saves space and makes editting the mapping a bit easier.

I'm happy to remove command from the function name and either use `set_dimensions` or `set_dimension_names` or even `map_dimensions`.

**Comment by davbyr** [comment]
Or if we want a super generic function for doing this, take the dictionary out of the function altogether. This could be kept in COAsT, then each sub-object thing contains it's own mapping dictionary which it passes on load/__init__.  So:
```
def set_command_dimensions(self, dim_mapping: dict=None):
    """ A method to relabel the domain dimensions for consistent
    and transparent use in this package:
    """
    for key, value in dim_mapping.items():
        try:
            self.dataset = self.dataset.rename_dims({ key : value })
        except: AttributeError as e:
            print('Problem mapping ' + key + ' to ' + value)
```
Then in, say, a NEMO object or DOMAIN object, just keep a default mapping dict somehwere to be used on load:
```
def set_mapping_dict():
    self.dim_mapping = {'t':'t_dim',
                       'z':'z_dim',
                       'y':'y_dim',
                       'x':'x_dim'}
```

In the case of multiple possible input names (e.g. for coordinates: longitude/long/lon/nav_lon), the key of the dictionary could be a tuple which it loops over until it finds one.

**Comment by jpolton** [comment]
> @jpolton I think this can work. It might be better to do it via an iteration through a mapping dictionary:
> 
> ```
> def set_command_dimensions(self, dim_mapping: dict=None):
>     """ A method to relabel the domain dimensions for consistent
>     and transparent use in this package:
>         t_dim - time
>         z_dim - depth
>         y_dim - northish (accepting that grids can be rotated)
>         x_dim - eastish (accepting that grids can be rotated)
>     """
>     if dim_mapping is None:
>         dim_mapping = {'t':'t_dim',
>                        'z':'z_dim',
>                        'y':'y_dim',
>                        'x':'x_dim'}
>     
>     for key, value in dim_mapping.items():
>         try:
>             self.dataset = self.dataset.rename_dims({ key : value })
>         except: AttributeError as e:
>             print('Problem mapping ' + key + ' to ' + value)
> ```
> 
> The default mapping dictionary can then be defined at the top of the function (to be used when loading) or a dictionary can be supplied as an argument by the user (if manual renaming is required). This is more relevant to variable renaming than dimension renaming, but a standard format might be good anyway. Also saves space and makes editting the mapping a bit easier.
> 
> I'm happy to remove command from the function name and either use `set_dimensions` or `set_dimension_names` or even `map_dimensions`.

I like the method rewrite as an iteration. ``set_dimension_names`` is the most clear title (`map` is an ambiguous term). I guess we want to replace ``set_command_variables`` -->  ``set_variable_names``

**Comment by davbyr** [comment]
Yeah map might be confusing, you're right. 

I'm happy to have a stab at implementing this if all are happy?

**Comment by jpolton** [comment]
An observation.
The above is setup that works well to map between list of known inputs and a list of know outputs. This is appropriate for things like dimension mapping. 
An alternative structure could map between a list of possible inputs and a specified output would work better for variables.

I would consider making these separate things, rather than expanding the key to be accommodate a list of possible inputs because though more concise it might get confusing to read for python novices

**Comment by jpolton** [comment]
> Yeah map might be confusing, you're right.
> 
> I'm happy to have a stab at implementing this if all are happy?

Go for it!

**Comment by jpolton** [comment]
@davbyr Are you happy to close this now that it has been picket up in a new ticket?

**Comment by davbyr** [comment]
@jpolton Yes, happy
