### ISSUE TITLE
Move netCDF --> remote server

### ISSUE THREAD

**Issue by jpolton** [British-Oceanographic-Data-Centre/COAsT#97]
Github is not the place for static binary netcdf files.

Migrate netCDF data in example_files to an ftp site or other accessible place where these static files can be obtained following a git clone.

Need to identify suitable storage location

AC:
* Files put somewhere else
* gitignore on example_files/*nc
* User is promoted to download files from code base (given url)
* purge git-lfs from repo

**Comment by malhearn** [comment]
Additional AC:
If someone does not have the data they are prompted to download with a URL

**Comment by thogar-computer** [comment]
@jpolton @davbyr @anwiseNOCL have a explain of this on our dev server (internal only) 

https://dev.linkedsystems.uk/erddap/files/COAsT_example_files/

**Comment by davbyr** [comment]
@thogar-computer I have already changed the tide gauge files in another branch which I just pushed (0089/STATS). Could you add these to the server instead of the originals please?

**Comment by thogar-computer** [comment]
> @thogar-computer I have already changed the tide gauge files in another branch which I just pushed (0089/STATS). Could you add these to the server instead of the originals please?

cool got those files 
cheers

**Comment by thogar-computer** [comment]
@davbyr @jpolton @anwiseNOCL 
the examples_Scripts and unit_testing code both look for the the example_files folder as part of this ticket i was expecting to remove this folder, is that correct?  

also I guess these folders are not going into the pypi/conda package?

I can do a simple check for the a dir called example_files, if not found I can give link to erddaped files and then wait for a response from the user asking for path to these files?

**Comment by jpolton** [comment]
> @davbyr @jpolton @anwiseNOCL
> the examples_Scripts and unit_testing code both look for the the example_files folder as part of this ticket i was expecting to remove this folder, is that correct?
> 
> also I guess these folders are not going into the pypi/conda package?
> 
> I can do a simple check for the a dir called example_files, if not found I can give link to erddaped files and then wait for a response from the user asking for path to these files?

@thogar-computer At present the `example_files` is a folder in the repo with a README listing its contents. I created this README so that the folder would exist in the cloned directory structure. The README tells the user to go get the files from Dropbox. You can do what ever you see fit to replace this functionality. (The README is not in itself important).

**Comment by jpolton** [comment]
Tested new file store location. All good.
